### ISSUE TITLE
Breakpoints in tests code are not hit but the ones in the source code works

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Testing#145]
Example:
https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNet.Mvc.Core.Test/Routing/InnerAttributeRouteTest.cs#L1428
None of the breakpoints in the test are hit. There is a warning in the breakpoint saying "No symbols have been loaded for this document". But the breakpoints in the source code `InnerAttributeRoute` are hit.
Dnx: `1.0.0-beta8-15519 clr     x86          win`

cc' @rynowak @NTaylorMullen

**Comment by rynowak** [comment]
When I've seen this, VS gives the "source doesn't match symbols" message. You can easily see this by putting a `System.Diagnostics.Debugger.Launch()` in the code and running it normally.

The likely cause is that somewhere in DNX we're doing something that causes it not to match. Needs more investigation to figure out the root cause.

**Comment by Eilon** [comment]
@davidfowl need info from you on this. Is there some source transformation that might happen for some files that could affect the debug info not matching? A missing BOM or something?
