### ISSUE TITLE
k test freezes in certain Powershell scripts

### ISSUE THREAD

**Issue by JamesNK** [aspnet/Testing#48]
I am executing k test inside a complex Powershell script that is using a PS function pointer. k test freezes after running many unit tests (I suspect it might be when one fails, or it might just be a large number, I have over 1500 tests) but the place it freezes isn't always the same. I don't know if it is important but my tests use Console.WriteLine a lot.

When k test freezes I am unable to even CTRL-C to cancel the script and have to close and reopen cmd.

    # k test is run inside CoreTests function
    # Arguments: k --configuration Release test -parallel none

    # this freezes:
    $TestsFunction = ${function:CoreTests}
    $TestsFunction.Invoke($build)

    # this works:
    CoreTests($build)

    # this works:
    &"CoreTests" $build

I am using PS 2.0, Windows 7 and CoreCLR 10580.

**Comment by rynowak** [comment]
Is this still causing issues? I am unable to repro this problem on newer bits.

I even added about 100000 lines of console output to some of our tests projects and couldn't see it hang.

One thing that I notice while trying to repro this is that using the function pointer `$TestsFunction.Invoke($build)` seems to buffer the console output. Running the tests this way prints all the console output at the end of execution instead of streaming out the lines one by one (as with `CoreTests($build)`). Some interaction between this and the console IO done by your tests might be causing the hang.

**Comment by JamesNK** [comment]
Dunno. I haven't run json.net unit tests on DNX since then.

**Comment by Eilon** [comment]
We haven't seen reports of this from anyone else so far. If you see this again please re-open.
