### ISSUE TITLE
Unable to discover tests after upgrade to CTP 5

### ISSUE THREAD

**Issue by kalluri-nb** [aspnet/Testing#64]
The discovery of tests is never ending and after an hour or so there will be no tests discovered.

![image](https://cloud.githubusercontent.com/assets/9352992/5847020/9433d2a6-a196-11e4-8404-95270924e6e2.png)

**Comment by aguacongas** [comment]
I've the same issue and in the test console I've this ouput:
------ Discover test started ------
An exception occurred while test discoverer 'KUnitTestDiscoverer' was loading tests. Exception: No connection could be made because the target machine actively refused it 127.0.0.1:16935
========== Discover test finished: 0 found (0:00:20.6218274) ==========

**Comment by rynowak** [comment]
Can you please try setting the environment variable `VS_UTE_Diagnostics = 1` and see if that adds any more info to the 'test' output window? 

@vijayrkn @mayurid @BillHiebert have you seen this issue before?

**Comment by aguacongas** [comment]
@rynowak I got the same output after setting this env var

**Comment by Eilon** [comment]
This is most likely fixed because we can't reproduce this anymore. We have also made improvements to the diagnostics reporting so if something does go wrong the Output Windows should have more info.
