### ISSUE TITLE
Flow errors back to VS

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Testing#83]

**Comment by vijayrkn** [comment]
Right now the runner only provides messages of type 
Discovery : TestDiscovery.TestFound & TestDiscovery.Response
Execution: TestExecution.TestStarted, TestExecution.TestResult and TestExecution.Response 

Runner needs to provide VS with Error messages ( if any) so that VS can display the error messages.

**Comment by rynowak** [comment]
Yep, for this item we need to updated TestHost to send back a `Message` message type.
- Start using this to actually log information in TestHost
- Implement an ILoggerFactory and provide it to the test runner so that it can log meanful information as well.

**Comment by rynowak** [comment]
f360d9265c7ca00e21d31bde7d72d853f9dfa7c4
